### ISSUE TITLE
Webdav connect to OneDrive

### ISSUE THREAD

**Issue by MarkLants** [yoichiro/chromeos-filesystem-webdav#9]
After setting up a OneDrive webdav server I click the Mount button and get NOT_FOUND.  What am I doing wrong?

**Comment by yoichiro** [comment]
@MarkLants Hmm... I want to try to access to OneDrive with WebDAV protocol using my application. Do you have the steps how to do it?

**Comment by MarkLants** [comment]
Here is the URL to directions http://www.intowindows.com/how-to-access-skydrive-without-microsoft-account-in-windows-8-1/

**Comment by MarkLants** [comment]
Here is the URL to directions:
http://www.intowindows.com/how-to-access-skydrive-without-microsoft-account-in-windows-8-1/

**Comment by yoichiro** [comment]
@MarkLants At least, I have already released "File System for OneDrive". You can mount your OneDrive with it. https://chrome.google.com/webstore/detail/file-system-for-onedrive/jbfdfcehgafdbfpniaimfbfomafoadgo

**Comment by MarkLants** [comment]
Thank you.   The app works great.   Do you plan on releasing an application
to connect to a NAS device (CIFS/smb protocols)?

**Comment by yoichiro** [comment]
@MarkLants I tried to access to OneDrive with this WebDAV implementation, but I had the same result. It seems finally redirected to the /pagenotfound URL... I guess that the OneDrive WebDAV server doesn't support the Basic authentication. Do you know whether the OneDrive WebDAV server can treat the Basic authentication or not?

Well, I want to develop the CIFS implementation, but, unfortunately, I don't have enough knowledge to develop it yet... I need to study the CIFS protocol more deeply...

**Comment by Yourdaguy** [comment]
I am also interested in connecting to my NAS.  Best would be by ip address since our router has static ip and the NAS has static DHCP behind it.  Awesome app by the way!  Thanks for doing it.

Bill Franklin
812-205-6321

**Comment by yoichiro** [comment]
Close this issue.
